# Generated by Django 4.2.2 on 2023-06-08 05:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=512),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=16384),
        ),
    ]
